name: CROUS Watcher

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:


jobs:
  check-crous:

    runs-on: ubuntu-latest

    steps:

      - name: Récupération du code
        uses: actions/checkout@v4


      - name: Installation Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Installation dépendances
        run: |
          pip install -r requirements.txt


      - name: Lancement du bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

        run: |
          python crous_watcher.py